#!/usr/bin/env bash
# installing nginx web server.
# echoing string 'Hello, world'

sudo apt update
sudo apt -y install nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
