#!/usr/bin/env bash
# installing nginx web server.
# echoing string 'Hello, world'

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee  /var/www/html/index.html
sudo service nginx restart
