#!/usr/bin/env bash
# Installs nginx web server and redirection

apt-get update
apt-get install -y nginx
echo "Hello World!" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://youtu.be/erLbbextvlY?si=y9yMuGavu4ku25JU;
    }
}" > /etc/nginx/sites-available/default
service nginx restart