#!/usr/bin/env bash
# display 'Best school' 10 times and 'Hi' for nineth iteration

counter=1

while [ $counter -le 10 ]; do
	
	if [ $counter -eq 9 ]; then
		echo "Hi"
	else
		echo "Best School"
	fi

	((counter++))
done
