#!/usr/bin/env bash
# display 'Best school' 10 times and 'Hi' for nineth iteration

counter=0

while [ $counter -lt 10 ]; do
	if [ $counter -eq 8 ]; then
		echo "Hi"
	else
		echo "Best School"
	fi

	((counter++))
done
