#!/usr/bin/env bash
# diplay 'bad luck' for the 4th loop iteration
# display 'good luck' for the 8th loop iteration
# display 'Best School' for the other iteration

counter=0

while [ $counter -lt 10 ]; do
	if [ $counter -eq 3 ]; then
		echo "bad luck"
	elif [ $counter -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	
	((counter++))
done
